Dashboard skeleton
hatchways/team-raspberry pull request #33
Opened 2020-07-27 16:58 UTC by KaminKevCrew

Here's the dashboard skeleton. Basic components are integrated and buttons function in navbar. 

Still todo: 
Styling the navbar so it looks correct. It's currently a little bit bunched up.
Setting up profile pic/username functionality once backend is fully set up.

2020-07-27 17:03 UTC, AlwaysHunt commented on client/src/App.js
> +          <Route oath="/" component={LoggedInNavBar} />
Think a typo happened here

2020-07-27 17:04 UTC, CharlieLe3 reviewed
Just a typo issue

2020-07-27 18:04 UTC, KaminKevCrew commented on client/src/App.js
> +          <Route oath="/" component={LoggedInNavBar} />
You are correct, thanks for the catch!

2020-07-29 04:58 UTC, kimcarey submitted a review, later dismissed
Looks good to me! I'll plan to build on top of it

2020-07-29 05:25 UTC, kimcarey commented
I loaded your branch locally and got this error (warning).
```
Proxy error: Could not proxy request /demo_avatar.png from localhost:3000 to http://localhost:5000.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
```
Looks like your may have forgotten to add the user icon? I don't see that file anywhere in the files, but it's referenced here `<Avatar alt="John Doe" src="demo_avatar.png" />`

2020-07-29 05:35 UTC, kimcarey requested changes
Seeing the updated navbar and the links change the url (good work!) but the placeholder content of the pages doesn't seem to work as they are just blank except the login page?
<img width="1216" alt="Screen Shot 2020-07-28 at 10 32 54 PM" src="https://user-images.githubusercontent.com/22139916/88760800-a5dc6880-d122-11ea-8a6d-c8b8e974365d.png">

2020-07-29 17:09 UTC, kimcarey approved these changes
LGTM! I just switched to your branch and re-ran the server and I'm seeing the div messages on each of the pages. Whoo hoo!!

2020-07-29 17:26 UTC, CharlieLe3 approved these changes

2020-07-29 18:12 UTC, merged